[package]
name = "dataset"
authors = ["Nico Wagner <n.wagner@dnb.de>"]
edition = "2021"
license = "EUPL-1.2"
rust-version = "1.79.0"
version = "0.1.0"

[[bin]]
name = "dataset"
path = "src/bin/main.rs"

[workspace]
members = ["crates/datapod"]
resolver = "2"

[workspace.package]
authors = ["Nico Wagner <n.wagner@dnb.de>"]
edition = "2021"
license = "EUPL-1.2"
rust-version = "1.79.0"

[workspace.dependencies]
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
thiserror = { version = "1.0" }
toml = { version = "0.8.14", features = ["preserve_order"] }

[workspace.dependencies.clap]
features = ["cargo", "derive", "wrap_help", "usage", "env"]
version = "4.5"

