[package]
name = "dataset"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
